name:                purs-doctest
version:             0.1.0.0
github:              "hdgarrood/purs-doctest"
license:             MIT
author:              "Harry Garrood"
maintainer:          "harry@garrood.me"
copyright:           "2017 Harry Garrood"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/purs-doctest#readme>

dependencies:
- base >= 4.7 && < 5
- purescript ==0.11.7
- cheapskate
- text
- Glob
- transformers
- bower-json
- boxes

library:
  source-dirs: src

executables:
  purs-doctest:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purs-doctest
    - base
    - directory
    - filepath
    - containers

tests:
  purs-doctest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purs-doctest
